--- Dockerfile-orig.txt	2023-07-19 16:18:20
+++ Dockerfile-edited.txt	2023-07-19 16:31:07
@@ -137,7 +137,13 @@
     -DLWS_WITH_STATIC=OFF"
 
 # Build guacamole-server and its core protocol library dependencies
-RUN ${BUILD_DIR}/src/guacd-docker/bin/build-all.sh
+ARG TARGETPLATFORM
+RUN echo "building for $TARGETPLATFORM"
+RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; \
+    then FREERDP_OPTS="${FREERDP_OPTS_COMMON}    -DWITH_SSE2=ON" && echo "SSE2 active"; \
+    else FREERDP_OPTS="${FREERDP_OPTS_COMMON}    -DWITH_SSE2=OFF" && echo "SSE2 disabled"; \
+    fi && \
+${BUILD_DIR}/src/guacd-docker/bin/build-all.sh
 
 # Record the packages of all runtime library dependencies
 RUN ${BUILD_DIR}/src/guacd-docker/bin/list-dependencies.sh \
